#!/usr/bin/env bash


INSTALL_DIR="$HOME"
if [ "$(uname)" == "Darwin" ]; then
    INSTALL_DIR="/usr/local"
fi



echo "We'll be uninstalling hoard ($INSTALL_DIR/bin/hoard) and all related files. [ctrl-c to cancel]"
sleep 2

(rm $INSTALL_DIR/bin/hoard >> /dev/null 2>&1 && echo "Uninstalled 'hoard' previously located at $INSTALL_DIR/bin/hoard")



if [[ -z "$HOARD_SESSIONS_PATH" ]]; then
    export HOARD_SESSIONS_PATH="$HOME/.hoard_sessions"
fi
if [[ -z "$HOARD_BOOKMARKS_PATH" ]]; then
    export HOARD_BOOKMARKS_PATH="$HOME/.hoard_bookmarks"
fi
rm "$HOARD_SESSIONS_PATH" >> /dev/null 2>&1
rm "$HOARD_BOOKMARKS_PATH" >> /dev/null 2>&1
echo "Deleted session and bookmark data."



file=
if [ -f "$HOME/.bashrc" ]; then
    file="$HOME/.bashrc"
elif [ -f "$HOME/.bash_profile" ]; then
    file="$HOME/.bash_profile"
elif [ -f "$HOME/.profile" ]; then
    file="$HOME/.profile"
fi



if [[ -z "$file" ]]; then
    echo "We've removed everything related to 'hoard'."
    echo "However, please remove '. hoard' from your .bashrc file or equivalent if you ever added that manually."
else
    if [ "$(uname)" == "Darwin" ]; then
        sed -i '' "/\. .*hoard$/g" "$file"
    else 
        sed -i "/\. .*hoard$/g" "$file"
    fi
    echo "We've removed everything related to 'hoard'."
fi
echo "Please restart all existing terminal windows to completely remove the ability to run 'hoard'."
